### ISSUE TITLE
Unitie logo in safari

### ISSUE THREAD

**Issue by officialunitie** [Unitie-FAC/Unitie-MVP#212]
unitie logo on safari when on brand page, INITIALLY does not come out properly. eventually returns to normal when you go onto another page and return to brand pages. Then goes back to its 'not normal form' when form is completed. Ive sent tormod a pic on whatsapp.

@thegsi @tormod17

**Comment by tormod17** [comment]
problem in safari v 6.0.5 but not in 6.1.6.

**Comment by tormod17** [comment]
@officialunitie is this issue fixed now ?

**Comment by officialunitie** [comment]
@tormod17 @thegsi  now, on the brand page, it initially comes out fine. but when sign up form is filled and submitted it returns to its old non-normal form

**Comment by officialunitie** [comment]
still not fixed, just checked. @tormod17 @thegsi 

not trying to be a pain, i am just very aware that many people will have previous versions of browsers, so its v.important that the sites functionality and aesthetics is of standard across the board

**Comment by thegsi** [comment]
@officialunitie We have just made some changes. Should work now.
